services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.12.0
    container_name: mealie
    restart: always
    ports:
        - "9050:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Denver
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://pancakefight.com
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_FROM_NAME: Pancake Fight
      SMTP_AUTH_STRATEGY: TLS
      SMTP_FROM_EMAIL: shaun.garwood@gmail.com
      SMTP_USER: shaun.garwood@gmail.com
      SMTP_PASSWORD: vedj olhe afnt yhtf

volumes:
  mealie-data:
