---
galaxy_info:
  author: csw
  description: YouTube synchronization service using TubeSync
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies:
  - role: docker
    when: youtube_sync_enabled | bool