---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
  become: yes

- name: Remove all Docker repository files
  shell: |
    rm -f /etc/apt/sources.list.d/docker*
    rm -f /etc/apt/keyrings/docker*
    rm -f /usr/share/keyrings/docker*
  become: yes
  ignore_errors: yes

- name: Update apt cache after cleanup
  apt:
    update_cache: yes
  become: yes
  ignore_errors: yes

- name: Install Docker using snap (alternative method)
  snap:
    name: docker
  become: yes



- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present
  become: yes